// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIciU4QgfsR3RZf6_u30gV3zx1fSxn8s',
    appId: '1:578469541776:web:c93de796d3de78b8dda515',
    messagingSenderId: '578469541776',
    projectId: 'gestion-com-796a6',
    authDomain: 'gestion-com-796a6.firebaseapp.com',
    storageBucket: 'gestion-com-796a6.firebasestorage.app',
    measurementId: 'G-QLLG7SNQ0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF8jHhOrFqD7EKPNhXWkFlUOdTetxaT8c',
    appId: '1:578469541776:android:06676f4642c45cb2dda515',
    messagingSenderId: '578469541776',
    projectId: 'gestion-com-796a6',
    storageBucket: 'gestion-com-796a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ65F9rh2PWz86ErwHg0-aM3zcF9C3X-I',
    appId: '1:578469541776:ios:080a0598c51df4f6dda515',
    messagingSenderId: '578469541776',
    projectId: 'gestion-com-796a6',
    storageBucket: 'gestion-com-796a6.firebasestorage.app',
    iosBundleId: 'com.example.samSamaAlal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ65F9rh2PWz86ErwHg0-aM3zcF9C3X-I',
    appId: '1:578469541776:ios:080a0598c51df4f6dda515',
    messagingSenderId: '578469541776',
    projectId: 'gestion-com-796a6',
    storageBucket: 'gestion-com-796a6.firebasestorage.app',
    iosBundleId: 'com.example.samSamaAlal',
  );
}
